INSERT INTO series (title, author_id, subgenre_id) VALUES ("The Chronicles of Narnia", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Harry Potter", 2, 21);
INSERT INTO books (title, year, series_id) VALUES ("The Lion, the Witch, and the Wardrobe", 2009, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Magician's Nephew", 2009, 2);
INSERT INTO books (title, year, series_id) VALUES ("Prince Caspian", 2009, 3);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter: The Prequel", 2008, 1);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Sorceror's Stone", 1997, 2);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Chamber of Secrets", 1998, 3); 
INSERT INTO characters (name, species, motto, author_id) VALUES ("Aslan", "diety", "Courage, dear heart!", 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Queen Lucy, the Valiant", "human", "I'm ready now.", 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Jadis, the White Witch", "Half-Jinn/Half-Giant", "If it's a war Aslan wants, it's a war he shall get.", 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Mr. Beaver,", "Semi-aquatic Rodent", "'Course he isn’t safe. But he’s good. He’s the King, I tell you.", 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Harry Potter", "Wizard", "One can never have enough socks.", 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Dobby", "Elf", "Socks are Dobby's favourite clothes, sir.", 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Lord Voldemort", "Half-blood", "There is no good and evil, there is only power and those too weak to seek it.", 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ("Professor Minverva McGonagall", "Half-blood", "They're supposed to be, you blithering idiot.", 2);
INSERT INTO authors (name) VALUES ("C. S. Lewis");
INSERT INTO authors (name) VALUES ("J. k. Rowling");
INSERT INTO subgenres (name) VALUES ("Action and Adventure");
INSERT INTO subgenres (name) VALUES ("Childrens");
